on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose build
      - run: docker compose up -d
      - run: docker compose logs db
        if: always()


      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if docker compose exec -T db pg_isready -U ci; then
              echo "Database is ready!"
              exit 0
            fi
            echo "Waiting for database..."
            sleep 2
          done
          echo "Database did not become ready in time!" && exit 1

      - run: pytest tests --junit-xml=tests-results.xml
        env:
          APP_URL: http://127.0.0.1:8002

      - run: docker compose logs app db
        if: always()
      - run: docker compose logs app
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: tests-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results